-- DDL file generated by ./generate_oracle_deployable.sh on 03132007124002
-- ====================================================
-- ====================================================
-- ====================================================
PROMPT Creating Tables
REM ======================================================================
REM ===   Sql Script for Database : DBS_NEW_ERA
REM ===
REM === Build : 628
REM ======================================================================

CREATE TABLE Person
  (
    ID                    integer,
    Name                  varchar(100),
    DistinguishedName     varchar(500)                                                      unique not null,
    ContactInfo           varchar(250),
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE Role
  (
    ID                    integer,
    RoleName              varchar(100)                                                      unique not null,
    RoleDescription       varchar(500)                                                      not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AssignedRole
  (
    ID                    integer,
    PersonID              integer                                                   not null,
    RoleID                integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE PhysicsGroup
  (
    ID                    integer,
    PhysicsGroupName      varchar(500)                                                      unique not null,
    PhysicsGroupConvener  integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE SchemaVersion
  (
    ID                    integer,
    SchemaVersion         varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE Runs
  (
    ID                    integer,
    RunNumber             integer                                                   unique not null,
    NumberOfEvents        integer                                                   not null,
    NumberOfLumiSections  integer                                                   not null,
    TotalLuminosity       integer                                                   not null,
    StoreNumber           integer                                                   not null,
    StartOfRun            varchar(100),
    EndOfRun              varchar(100),
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE DataTier
  (
    ID                    integer,
    Name                  varchar(100)                                                      unique not null,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE LumiSection
  (
    ID                    integer,
    LumiSectionNumber     integer                                                   not null,
    RunNumber             integer                                                   not null,
    StartEventNumber      integer                                                   not null,
    EndEventNumber        integer                                                   not null,
    LumiStartTime         varchar(100),
    LumiEndTime           varchar(100),
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID),
    unique(LumiSectionNumber,RunNumber)
  );

REM ======================================================================

CREATE TABLE Branch
  (
    ID                    integer,
    Name                  varchar(500)                                                      unique not null,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE TimeLog
  (
    ID                    integer,
    Action                varchar(100)          not null,
    Cause                 varchar(100)          not null,
    Effect                varchar(100)          not null,
    Description           varchar(500)          not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE DataTierOrder
  (
    ID                    integer,
    DataTierOrder         varchar(250)                                                      unique not null,
    Description           varchar(1000),
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AppFamily
  (
    ID                    integer,
    FamilyName            varchar(100)                                                      unique not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AppVersion
  (
    ID                    integer,
    Version               varchar(100)                                                      unique not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AppExecutable
  (
    ID                    integer,
    ExecutableName        varchar(100)                                                      unique not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE QueryableParameterSet
  (
    ID                    integer,
    Hash                  varchar(700)                                                      unique not null,
    Name                  varchar(1000),
    Version               varchar(100),
    Type                  varchar(100),
    Annotation            varchar(1000),
    Content               CLOB,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE ParameterBinding
  (
    ID                    integer,
    Self                  integer                                                   not null,
    Contains              integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE TriggerPathDescription
  (
    ID                      integer,
    TriggerPathDescription  varchar(100)                                                      unique not null,
    CreatedBy               integer,
    CreationDate            TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy          integer,
    LastModificationDate    TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE MCDescription
  (
    ID                    integer,
    MCChannelDescription  varchar(100)                                                      not null,
    MCProduction          varchar(100),
    MCDecayChain          varchar(100),
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID),
    unique(MCChannelDescription,MCProduction,MCDecayChain)
  );

REM ======================================================================

CREATE TABLE OtherDescription
  (
    ID                    integer,
    Description           varchar(100)                                                      unique not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE FileStatus
  (
    ID                    integer,
    Status                varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE FileType
  (
    ID                    integer,
    Type                  varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE FileValidStatus
  (
    ID                    integer,
    Status                varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AnalysisDSType
  (
    ID                    integer,
    Type                  varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AnalysisDSStatus
  (
    ID                    integer,
    Status                varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AnalysisDSDef
  (
    ID                    integer,
    Name                  varchar(700)                                                      unique not null,
    LumiSections          CLOB,
    LumiSectionRanges     CLOB,
    Runs                  CLOB,
    RunsRanges            CLOB,
    Algorithms            varchar(1000),
    LFNs                  CLOB,
    Path                  varchar(1000),
    Tiers                 varchar(250),
    AnalysisDatasets      CLOB,
    UserCut               CLOB,
    Description           CLOB,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE StorageElement
  (
    ID                    integer,
    SEName                varchar(500)                                                      unique not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE ProcDSStatus
  (
    ID                    integer,
    Status                varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE PrimaryDSType
  (
    ID                    integer,
    Type                  varchar(100)                                                      unique not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE AlgorithmConfig
  (
    ID                    integer,
    ExecutableName        integer                                                   not null,
    ApplicationVersion    integer                                                   not null,
    ApplicationFamily     integer                                                   not null,
    ParameterSetID        integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(ExecutableName,ApplicationVersion,ApplicationFamily,ParameterSetID)
  );

REM ======================================================================

CREATE TABLE PrimaryDatasetDescription
  (
    ID                      integer,
    TriggerDescriptionID    integer,
    MCChannelDescriptionID  integer,
    OtherDescriptionID      integer,
    CreatedBy               integer,
    CreationDate            TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy          integer,
    LastModificationDate    TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID),
    unique(TriggerDescriptionID,MCChannelDescriptionID,OtherDescriptionID)
  );

REM ======================================================================

CREATE TABLE PrimaryDataset
  (
    ID                    integer,
    Name                  varchar(100)                                                      unique not null,
    Annotation            varchar(1000)                                                     not null,
    Description           integer,
    StartDate             varchar(100),
    EndDate               varchar(100),
    Type                  integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE ProcessedDataset
  (
    ID                    integer,
    Name                  varchar(500)                                                      not null,
    PrimaryDataset        integer                                                   not null,
    PhysicsGroup          integer                                                   not null,
    Status                integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID),
    unique(Name,PrimaryDataset)
  );

REM ======================================================================

CREATE TABLE AnalysisDataset
  (
    ID                    integer,
    Name                  varchar(500)                                                      unique not null,
    Annotation            varchar(1000)                                                     not null,
    ProcessedDS           integer                                                   not null,
    Definition            integer                                                   not null,
    Type                  integer                                                   not null,
    Status                integer                                                   not null,
    Parent                integer,
    PhysicsGroup          integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE ProcDSRuns
  (
    ID                    integer,
    Dataset               integer                                                   not null,
    Run                   integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Dataset,Run)
  );

REM ======================================================================

CREATE TABLE ProcDSTier
  (
    ID                    integer,
    Dataset               integer                                                   not null,
    DataTier              integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Dataset,DataTier)
  );

REM ======================================================================

CREATE TABLE ProcDSParent
  (
    ID                    integer,
    ThisDataset           integer                                                   not null,
    ItsParent             integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID),
    unique(ThisDataset,ItsParent)
  );

REM ======================================================================

CREATE TABLE ProcAlgo
  (
    ID                    integer,
    Dataset               integer                                                   not null,
    Algorithm             integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Dataset,Algorithm)
  );

REM ======================================================================

CREATE TABLE Block
  (
    ID                    integer,
    Name                  varchar(500)                                                      unique not null,
    Path                  varchar(500)                                                      not null,
    Dataset               integer                                                   not null,
    BlockSize             integer                                                   not null,
    NumberOfFiles         integer                                                   not null,
    NumberOfEvents        integer                                                   not null,
    OpenForWriting        integer                                                               not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE Files
  (
    ID                    integer,
    LogicalFileName       varchar(500)                                                      unique not null,
    Dataset               integer                                                   not null,
    Block                 integer                                                   not null,
    Checksum              varchar(100)                                                      not null,
    NumberOfEvents        integer                                                   not null,
    FileSize              integer                                                   not null,
    FileStatus            integer                                                   not null,
    FileType              integer                                                   not null,
    ValidationStatus      integer,
    QueryableMetadata     varchar(1000),
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID)
  );

REM ======================================================================

CREATE TABLE FileTier
  (
    ID                    integer,
    Fileid                integer                                                   not null,
    DataTier              integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Fileid,DataTier)
  );

REM ======================================================================

CREATE TABLE FileParentage
  (
    ID                    integer,
    ThisFile              integer                                                   not null,
    ItsParent             integer                                                   not null,
    CreatedBy             integer,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    primary key(ID),
    unique(ThisFile,ItsParent)
  );

REM ======================================================================

CREATE TABLE FileRunLumi
  (
    ID                    integer,
    Fileid                integer                                                   not null,
    Lumi                  integer,
    Run                   integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Fileid,Lumi,Run)
  );

REM ======================================================================

CREATE TABLE FileAlgo
  (
    ID                    integer,
    Fileid                integer                                                   not null,
    Algorithm             integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Fileid,Algorithm)
  );

REM ======================================================================

CREATE TABLE FileBranch
  (
    ID                    integer,
    Fileid                integer                                                   not null,
    Branch                integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(Fileid,Branch)
  );

REM ======================================================================

CREATE TABLE AnalysisDSFileLumi
  (
    ID                    integer,
    AnalysisDataset       integer                                                   not null,
    Lumi                  integer,
    Fileid                integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(AnalysisDataset,Lumi,Fileid)
  );

REM ======================================================================

CREATE TABLE SEBlock
  (
    ID                    integer,
    SEID                  integer                                                   not null,
    BlockID               integer                                                   not null,
    CreationDate          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CreatedBy             integer,
    LastModificationDate  TIMESTAMP DEFAULT SYSTIMESTAMP,
    LastModifiedBy        integer,
    primary key(ID),
    unique(SEID,BlockID)
  );

REM ======================================================================

ALTER TABLE Person ADD CONSTRAINT 
    Person_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE Person ADD CONSTRAINT 
    Person_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE Role ADD CONSTRAINT 
    Role_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE Role ADD CONSTRAINT 
    Role_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AssignedRole ADD CONSTRAINT 
    AssignedRole_PersonID_FK foreign key(PersonID) references Person(ID)
/
ALTER TABLE AssignedRole ADD CONSTRAINT 
    AssignedRole_RoleID_FK foreign key(RoleID) references Role(ID)
/
ALTER TABLE AssignedRole ADD CONSTRAINT 
    AssignedRole_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AssignedRole ADD CONSTRAINT 
    AssignedRole_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE PhysicsGroup ADD CONSTRAINT 
    PhysicsGroupPhysicsGroupCon_FK foreign key(PhysicsGroupConvener) references Person(ID)
/
ALTER TABLE PhysicsGroup ADD CONSTRAINT 
    PhysicsGroup_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE PhysicsGroup ADD CONSTRAINT 
    PhysicsGroup_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE SchemaVersion ADD CONSTRAINT 
    SchemaVersion_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE SchemaVersion ADD CONSTRAINT 
    SchemaVersionLastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE Runs ADD CONSTRAINT 
    Runs_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE Runs ADD CONSTRAINT 
    Runs_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE DataTier ADD CONSTRAINT 
    DataTier_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/
ALTER TABLE DataTier ADD CONSTRAINT 
    DataTier_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/

ALTER TABLE LumiSection ADD CONSTRAINT 
    LumiSection_RunNumber_FK foreign key(RunNumber) references Runs(ID)
/
ALTER TABLE LumiSection ADD CONSTRAINT 
    LumiSection_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE LumiSection ADD CONSTRAINT 
    LumiSection_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE Branch ADD CONSTRAINT 
    Branch_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/
ALTER TABLE Branch ADD CONSTRAINT 
    Branch_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/

ALTER TABLE TimeLog ADD CONSTRAINT 
    TimeLog_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/

ALTER TABLE DataTierOrder ADD CONSTRAINT 
    DataTierOrder_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/

ALTER TABLE AppFamily ADD CONSTRAINT 
    AppFamily_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AppFamily ADD CONSTRAINT 
    AppFamily_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AppVersion ADD CONSTRAINT 
    AppVersion_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AppVersion ADD CONSTRAINT 
    AppVersion_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AppExecutable ADD CONSTRAINT 
    AppExecutable_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AppExecutable ADD CONSTRAINT 
    AppExecutableLastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE QueryableParameterSet ADD CONSTRAINT 
    QueryableParameterSetCreate_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE QueryableParameterSet ADD CONSTRAINT 
    QueryableParameterSetLastMo_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ParameterBinding ADD CONSTRAINT 
    ParameterBinding_Self_FK foreign key(Self) references QueryableParameterSet(ID)
/
ALTER TABLE ParameterBinding ADD CONSTRAINT 
    ParameterBinding_Contains_FK foreign key(Contains) references QueryableParameterSet(ID)
/
ALTER TABLE ParameterBinding ADD CONSTRAINT 
    ParameterBinding_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ParameterBinding ADD CONSTRAINT 
    ParameterBindingLastModifie_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE TriggerPathDescription ADD CONSTRAINT 
    TriggerPathDescriptionCreat_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE TriggerPathDescription ADD CONSTRAINT 
    TriggerPathDescriptionLastM_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE MCDescription ADD CONSTRAINT 
    MCDescription_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE MCDescription ADD CONSTRAINT 
    MCDescriptionLastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE OtherDescription ADD CONSTRAINT 
    OtherDescription_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE OtherDescription ADD CONSTRAINT 
    OtherDescriptionLastModifie_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileStatus ADD CONSTRAINT 
    FileStatus_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileStatus ADD CONSTRAINT 
    FileStatus_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileType ADD CONSTRAINT 
    FileType_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileType ADD CONSTRAINT 
    FileType_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileValidStatus ADD CONSTRAINT 
    FileValidStatus_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileValidStatus ADD CONSTRAINT 
    FileValidStatusLastModified_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AnalysisDSType ADD CONSTRAINT 
    AnalysisDSType_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AnalysisDSType ADD CONSTRAINT 
    AnalysisDSTypeLastModifiedB_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AnalysisDSStatus ADD CONSTRAINT 
    AnalysisDSStatus_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AnalysisDSStatus ADD CONSTRAINT 
    AnalysisDSStatusLastModifie_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AnalysisDSDef ADD CONSTRAINT 
    AnalysisDSDef_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AnalysisDSDef ADD CONSTRAINT 
    AnalysisDSDefLastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE StorageElement ADD CONSTRAINT 
    StorageElement_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE StorageElement ADD CONSTRAINT 
    StorageElementLastModifiedB_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ProcDSStatus ADD CONSTRAINT 
    ProcDSStatus_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ProcDSStatus ADD CONSTRAINT 
    ProcDSStatus_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE PrimaryDSType ADD CONSTRAINT 
    PrimaryDSType_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE PrimaryDSType ADD CONSTRAINT 
    PrimaryDSTypeLastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AlgorithmConfig ADD CONSTRAINT 
    AlgorithmConfigExecutableNa_FK foreign key(ExecutableName) references AppExecutable(ID)
/
ALTER TABLE AlgorithmConfig ADD CONSTRAINT 
    AlgorithmConfigApplicationV_FK foreign key(ApplicationVersion) references AppVersion(ID)
/
ALTER TABLE AlgorithmConfig ADD CONSTRAINT 
    AlgorithmConfigApplicationF_FK foreign key(ApplicationFamily) references AppFamily(ID)
/
ALTER TABLE AlgorithmConfig ADD CONSTRAINT 
    AlgorithmConfigParameterSet_FK foreign key(ParameterSetID) references QueryableParameterSet(ID)
/
ALTER TABLE AlgorithmConfig ADD CONSTRAINT 
    AlgorithmConfig_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AlgorithmConfig ADD CONSTRAINT 
    AlgorithmConfigLastModified_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE PrimaryDatasetDescription ADD CONSTRAINT 
    PrimaryDatasetDescriptionTr_FK foreign key(TriggerDescriptionID) references TriggerPathDescription(ID)
/
ALTER TABLE PrimaryDatasetDescription ADD CONSTRAINT 
    PrimaryDatasetDescriptionMC_FK foreign key(MCChannelDescriptionID) references MCDescription(ID)
/
ALTER TABLE PrimaryDatasetDescription ADD CONSTRAINT 
    PrimaryDatasetDescriptionOt_FK foreign key(OtherDescriptionID) references OtherDescription(ID)
/
ALTER TABLE PrimaryDatasetDescription ADD CONSTRAINT 
    PrimaryDatasetDescriptionCr_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE PrimaryDatasetDescription ADD CONSTRAINT 
    PrimaryDatasetDescriptionLa_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE PrimaryDataset ADD CONSTRAINT 
    PrimaryDataset_Description_FK foreign key(Description) references PrimaryDatasetDescription(ID)
/
ALTER TABLE PrimaryDataset ADD CONSTRAINT 
    PrimaryDataset_Type_FK foreign key(Type) references PrimaryDSType(ID)
/
ALTER TABLE PrimaryDataset ADD CONSTRAINT 
    PrimaryDataset_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE PrimaryDataset ADD CONSTRAINT 
    PrimaryDatasetLastModifiedB_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ProcessedDataset ADD CONSTRAINT 
    ProcessedDatasetPrimaryData_FK foreign key(PrimaryDataset) references PrimaryDataset(ID) on delete CASCADE
/
ALTER TABLE ProcessedDataset ADD CONSTRAINT 
    ProcessedDatasetPhysicsGrou_FK foreign key(PhysicsGroup) references PhysicsGroup(ID)
/
ALTER TABLE ProcessedDataset ADD CONSTRAINT 
    ProcessedDataset_Status_FK foreign key(Status) references ProcDSStatus(ID)
/
ALTER TABLE ProcessedDataset ADD CONSTRAINT 
    ProcessedDataset_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ProcessedDataset ADD CONSTRAINT 
    ProcessedDatasetLastModifie_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDataset_ProcessedDS_FK foreign key(ProcessedDS) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDataset_Definition_FK foreign key(Definition) references AnalysisDSDef(ID)
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDataset_Type_FK foreign key(Type) references AnalysisDSType(ID)
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDataset_Status_FK foreign key(Status) references AnalysisDSStatus(ID)
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDataset_Parent_FK foreign key(Parent) references AnalysisDataset(ID)
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDatasetPhysicsGroup_FK foreign key(PhysicsGroup) references PhysicsGroup(ID)
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDataset_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AnalysisDataset ADD CONSTRAINT 
    AnalysisDatasetLastModified_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ProcDSRuns ADD CONSTRAINT 
    ProcDSRuns_Dataset_FK foreign key(Dataset) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE ProcDSRuns ADD CONSTRAINT 
    ProcDSRuns_Run_FK foreign key(Run) references Runs(ID)
/
ALTER TABLE ProcDSRuns ADD CONSTRAINT 
    ProcDSRuns_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ProcDSRuns ADD CONSTRAINT 
    ProcDSRuns_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ProcDSTier ADD CONSTRAINT 
    ProcDSTier_Dataset_FK foreign key(Dataset) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE ProcDSTier ADD CONSTRAINT 
    ProcDSTier_DataTier_FK foreign key(DataTier) references DataTier(ID)
/
ALTER TABLE ProcDSTier ADD CONSTRAINT 
    ProcDSTier_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ProcDSTier ADD CONSTRAINT 
    ProcDSTier_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ProcDSParent ADD CONSTRAINT 
    ProcDSParent_ThisDataset_FK foreign key(ThisDataset) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE ProcDSParent ADD CONSTRAINT 
    ProcDSParent_ItsParent_FK foreign key(ItsParent) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE ProcDSParent ADD CONSTRAINT 
    ProcDSParent_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ProcDSParent ADD CONSTRAINT 
    ProcDSParent_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE ProcAlgo ADD CONSTRAINT 
    ProcAlgo_Dataset_FK foreign key(Dataset) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE ProcAlgo ADD CONSTRAINT 
    ProcAlgo_Algorithm_FK foreign key(Algorithm) references AlgorithmConfig(ID) on delete CASCADE
/
ALTER TABLE ProcAlgo ADD CONSTRAINT 
    ProcAlgo_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE ProcAlgo ADD CONSTRAINT 
    ProcAlgo_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE Block ADD CONSTRAINT 
    Block_Dataset_FK foreign key(Dataset) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE Block ADD CONSTRAINT 
    Block_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE Block ADD CONSTRAINT 
    Block_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE Files ADD CONSTRAINT 
    Files_Dataset_FK foreign key(Dataset) references ProcessedDataset(ID) on delete CASCADE
/
ALTER TABLE Files ADD CONSTRAINT 
    Files_Block_FK foreign key(Block) references Block(ID) on delete CASCADE
/
ALTER TABLE Files ADD CONSTRAINT 
    Files_FileStatus_FK foreign key(FileStatus) references FileStatus(ID)
/
ALTER TABLE Files ADD CONSTRAINT 
    Files_FileType_FK foreign key(FileType) references FileType(ID)
/
ALTER TABLE Files ADD CONSTRAINT 
    Files_ValidationStatus_FK foreign key(ValidationStatus) references FileValidStatus(ID)
/
ALTER TABLE Files ADD CONSTRAINT 
    Files_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE Files ADD CONSTRAINT 
    Files_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileTier ADD CONSTRAINT 
    FileTier_Fileid_FK foreign key(Fileid) references Files(ID) on delete CASCADE
/
ALTER TABLE FileTier ADD CONSTRAINT 
    FileTier_DataTier_FK foreign key(DataTier) references DataTier(ID)
/
ALTER TABLE FileTier ADD CONSTRAINT 
    FileTier_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileTier ADD CONSTRAINT 
    FileTier_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileParentage ADD CONSTRAINT 
    FileParentage_ThisFile_FK foreign key(ThisFile) references Files(ID) on delete CASCADE
/
ALTER TABLE FileParentage ADD CONSTRAINT 
    FileParentage_ItsParent_FK foreign key(ItsParent) references Files(ID) on delete CASCADE
/
ALTER TABLE FileParentage ADD CONSTRAINT 
    FileParentage_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileParentage ADD CONSTRAINT 
    FileParentageLastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileRunLumi ADD CONSTRAINT 
    FileRunLumi_Fileid_FK foreign key(Fileid) references Files(ID) on delete CASCADE
/
ALTER TABLE FileRunLumi ADD CONSTRAINT 
    FileRunLumi_Lumi_FK foreign key(Lumi) references LumiSection(ID)
/
ALTER TABLE FileRunLumi ADD CONSTRAINT 
    FileRunLumi_Run_FK foreign key(Run) references Runs(ID)
/
ALTER TABLE FileRunLumi ADD CONSTRAINT 
    FileRunLumi_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileRunLumi ADD CONSTRAINT 
    FileRunLumi_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileAlgo ADD CONSTRAINT 
    FileAlgo_Fileid_FK foreign key(Fileid) references Files(ID) on delete CASCADE
/
ALTER TABLE FileAlgo ADD CONSTRAINT 
    FileAlgo_Algorithm_FK foreign key(Algorithm) references AlgorithmConfig(ID)
/
ALTER TABLE FileAlgo ADD CONSTRAINT 
    FileAlgo_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileAlgo ADD CONSTRAINT 
    FileAlgo_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE FileBranch ADD CONSTRAINT 
    FileBranch_Fileid_FK foreign key(Fileid) references Files(ID) on delete CASCADE
/
ALTER TABLE FileBranch ADD CONSTRAINT 
    FileBranch_Branch_FK foreign key(Branch) references Branch(ID)
/
ALTER TABLE FileBranch ADD CONSTRAINT 
    FileBranch_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE FileBranch ADD CONSTRAINT 
    FileBranch_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE AnalysisDSFileLumi ADD CONSTRAINT 
    AnalysisDSFileLumiAnalysisD_FK foreign key(AnalysisDataset) references AnalysisDataset(ID) on delete CASCADE
/
ALTER TABLE AnalysisDSFileLumi ADD CONSTRAINT 
    AnalysisDSFileLumi_Lumi_FK foreign key(Lumi) references LumiSection(ID)
/
ALTER TABLE AnalysisDSFileLumi ADD CONSTRAINT 
    AnalysisDSFileLumi_Fileid_FK foreign key(Fileid) references Files(ID)
/
ALTER TABLE AnalysisDSFileLumi ADD CONSTRAINT 
    AnalysisDSFileLumiCreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE AnalysisDSFileLumi ADD CONSTRAINT 
    AnalysisDSFileLumiLastModif_FK foreign key(LastModifiedBy) references Person(ID)
/

ALTER TABLE SEBlock ADD CONSTRAINT 
    SEBlock_SEID_FK foreign key(SEID) references StorageElement(ID)
/
ALTER TABLE SEBlock ADD CONSTRAINT 
    SEBlock_BlockID_FK foreign key(BlockID) references Block(ID)
/
ALTER TABLE SEBlock ADD CONSTRAINT 
    SEBlock_CreatedBy_FK foreign key(CreatedBy) references Person(ID)
/
ALTER TABLE SEBlock ADD CONSTRAINT 
    SEBlock_LastModifiedBy_FK foreign key(LastModifiedBy) references Person(ID)
/




-- === generated index statements ==============
PROMPT Creating indexes
create index ix_person_name on Person (Name);
create index ix_processeddataset_name on ProcessedDataset (Name);
create index ix_analysisdataset_annotation on AnalysisDataset (Annotation);
-- ====================================================

-- ============== SEQUENCES ===========================
PROMPT Creating sequences
create sequence seq_person ;
create sequence seq_role ;
create sequence seq_assignedrole ;
create sequence seq_physicsgroup ;
create sequence seq_schemaversion ;
create sequence seq_runs ;
create sequence seq_datatier ;
create sequence seq_lumisection ;
create sequence seq_branch ;
create sequence seq_timelog ;
create sequence seq_datatierorder ;
create sequence seq_appfamily ;
create sequence seq_appversion ;
create sequence seq_appexecutable ;
create sequence seq_queryableparameterset ;
create sequence seq_parameterbinding ;
create sequence seq_triggerpathdescription ;
create sequence seq_mcdescription ;
create sequence seq_otherdescription ;
create sequence seq_filestatus ;
create sequence seq_filetype ;
create sequence seq_filevalidstatus ;
create sequence seq_analysisdstype ;
create sequence seq_analysisdsstatus ;
create sequence seq_analysisdsdef ;
create sequence seq_storageelement ;
create sequence seq_procdsstatus ;
create sequence seq_primarydstype ;
create sequence seq_algorithmconfig ;
create sequence seq_primarydatasetdescription ;
create sequence seq_primarydataset ;
create sequence seq_processeddataset ;
create sequence seq_analysisdataset ;
create sequence seq_procdsruns ;
create sequence seq_procdstier ;
create sequence seq_procdsparent ;
create sequence seq_procalgo ;
create sequence seq_block ;
create sequence seq_files ;
create sequence seq_filetier ;
create sequence seq_fileparentage ;
create sequence seq_filerunlumi ;
create sequence seq_filealgo ;
create sequence seq_filebranch ;
create sequence seq_analysisdsfilelumi ;
create sequence seq_seblock ;
-- ============= AUTO INC Table.ID TRIGGERS ===========
PROMPT Creating auto inc triggers

-- ====================================================
-- AUTO INC TRIGGER FOR person.ID using SEQ seq_person

 CREATE OR REPLACE TRIGGER person_TRIG before insert on person    for each row begin     if inserting then       if :NEW.ID is null then          select seq_person.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR role.ID using SEQ seq_role

 CREATE OR REPLACE TRIGGER role_TRIG before insert on role    for each row begin     if inserting then       if :NEW.ID is null then          select seq_role.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR assignedrole.ID using SEQ seq_assignedrole

 CREATE OR REPLACE TRIGGER assignedrole_TRIG before insert on assignedrole    for each row begin     if inserting then       if :NEW.ID is null then          select seq_assignedrole.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR physicsgroup.ID using SEQ seq_physicsgroup

 CREATE OR REPLACE TRIGGER physicsgroup_TRIG before insert on physicsgroup    for each row begin     if inserting then       if :NEW.ID is null then          select seq_physicsgroup.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR schemaversion.ID using SEQ seq_schemaversion

 CREATE OR REPLACE TRIGGER schemaversion_TRIG before insert on schemaversion    for each row begin     if inserting then       if :NEW.ID is null then          select seq_schemaversion.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR runs.ID using SEQ seq_runs

 CREATE OR REPLACE TRIGGER runs_TRIG before insert on runs    for each row begin     if inserting then       if :NEW.ID is null then          select seq_runs.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR datatier.ID using SEQ seq_datatier

 CREATE OR REPLACE TRIGGER datatier_TRIG before insert on datatier    for each row begin     if inserting then       if :NEW.ID is null then          select seq_datatier.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR lumisection.ID using SEQ seq_lumisection

 CREATE OR REPLACE TRIGGER lumisection_TRIG before insert on lumisection    for each row begin     if inserting then       if :NEW.ID is null then          select seq_lumisection.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR branch.ID using SEQ seq_branch

 CREATE OR REPLACE TRIGGER branch_TRIG before insert on branch    for each row begin     if inserting then       if :NEW.ID is null then          select seq_branch.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR timelog.ID using SEQ seq_timelog

 CREATE OR REPLACE TRIGGER timelog_TRIG before insert on timelog    for each row begin     if inserting then       if :NEW.ID is null then          select seq_timelog.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR datatierorder.ID using SEQ seq_datatierorder

 CREATE OR REPLACE TRIGGER datatierorder_TRIG before insert on datatierorder    for each row begin     if inserting then       if :NEW.ID is null then          select seq_datatierorder.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR appfamily.ID using SEQ seq_appfamily

 CREATE OR REPLACE TRIGGER appfamily_TRIG before insert on appfamily    for each row begin     if inserting then       if :NEW.ID is null then          select seq_appfamily.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR appversion.ID using SEQ seq_appversion

 CREATE OR REPLACE TRIGGER appversion_TRIG before insert on appversion    for each row begin     if inserting then       if :NEW.ID is null then          select seq_appversion.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR appexecutable.ID using SEQ seq_appexecutable

 CREATE OR REPLACE TRIGGER appexecutable_TRIG before insert on appexecutable    for each row begin     if inserting then       if :NEW.ID is null then          select seq_appexecutable.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR queryableparameterset.ID using SEQ seq_queryableparameterset

 CREATE OR REPLACE TRIGGER queryableparameterset_TRIG before insert on queryableparameterset    for each row begin     if inserting then       if :NEW.ID is null then          select seq_queryableparameterset.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR parameterbinding.ID using SEQ seq_parameterbinding

 CREATE OR REPLACE TRIGGER parameterbinding_TRIG before insert on parameterbinding    for each row begin     if inserting then       if :NEW.ID is null then          select seq_parameterbinding.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR triggerpathdescription.ID using SEQ seq_triggerpathdescription

 CREATE OR REPLACE TRIGGER triggerpathdescription_TRIG before insert on triggerpathdescription    for each row begin     if inserting then       if :NEW.ID is null then          select seq_triggerpathdescription.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR mcdescription.ID using SEQ seq_mcdescription

 CREATE OR REPLACE TRIGGER mcdescription_TRIG before insert on mcdescription    for each row begin     if inserting then       if :NEW.ID is null then          select seq_mcdescription.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR otherdescription.ID using SEQ seq_otherdescription

 CREATE OR REPLACE TRIGGER otherdescription_TRIG before insert on otherdescription    for each row begin     if inserting then       if :NEW.ID is null then          select seq_otherdescription.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filestatus.ID using SEQ seq_filestatus

 CREATE OR REPLACE TRIGGER filestatus_TRIG before insert on filestatus    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filestatus.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filetype.ID using SEQ seq_filetype

 CREATE OR REPLACE TRIGGER filetype_TRIG before insert on filetype    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filetype.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filevalidstatus.ID using SEQ seq_filevalidstatus

 CREATE OR REPLACE TRIGGER filevalidstatus_TRIG before insert on filevalidstatus    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filevalidstatus.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR analysisdstype.ID using SEQ seq_analysisdstype

 CREATE OR REPLACE TRIGGER analysisdstype_TRIG before insert on analysisdstype    for each row begin     if inserting then       if :NEW.ID is null then          select seq_analysisdstype.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR analysisdsstatus.ID using SEQ seq_analysisdsstatus

 CREATE OR REPLACE TRIGGER analysisdsstatus_TRIG before insert on analysisdsstatus    for each row begin     if inserting then       if :NEW.ID is null then          select seq_analysisdsstatus.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR analysisdsdef.ID using SEQ seq_analysisdsdef

 CREATE OR REPLACE TRIGGER analysisdsdef_TRIG before insert on analysisdsdef    for each row begin     if inserting then       if :NEW.ID is null then          select seq_analysisdsdef.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR storageelement.ID using SEQ seq_storageelement

 CREATE OR REPLACE TRIGGER storageelement_TRIG before insert on storageelement    for each row begin     if inserting then       if :NEW.ID is null then          select seq_storageelement.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR procdsstatus.ID using SEQ seq_procdsstatus

 CREATE OR REPLACE TRIGGER procdsstatus_TRIG before insert on procdsstatus    for each row begin     if inserting then       if :NEW.ID is null then          select seq_procdsstatus.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR primarydstype.ID using SEQ seq_primarydstype

 CREATE OR REPLACE TRIGGER primarydstype_TRIG before insert on primarydstype    for each row begin     if inserting then       if :NEW.ID is null then          select seq_primarydstype.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR algorithmconfig.ID using SEQ seq_algorithmconfig

 CREATE OR REPLACE TRIGGER algorithmconfig_TRIG before insert on algorithmconfig    for each row begin     if inserting then       if :NEW.ID is null then          select seq_algorithmconfig.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR primarydatasetdescription.ID using SEQ seq_primarydatasetdescription

 CREATE OR REPLACE TRIGGER primarydatasetdescription_TRIG before insert on primarydatasetdescription    for each row begin     if inserting then       if :NEW.ID is null then          select seq_primarydatasetdescription.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR primarydataset.ID using SEQ seq_primarydataset

 CREATE OR REPLACE TRIGGER primarydataset_TRIG before insert on primarydataset    for each row begin     if inserting then       if :NEW.ID is null then          select seq_primarydataset.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR processeddataset.ID using SEQ seq_processeddataset

 CREATE OR REPLACE TRIGGER processeddataset_TRIG before insert on processeddataset    for each row begin     if inserting then       if :NEW.ID is null then          select seq_processeddataset.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR analysisdataset.ID using SEQ seq_analysisdataset

 CREATE OR REPLACE TRIGGER analysisdataset_TRIG before insert on analysisdataset    for each row begin     if inserting then       if :NEW.ID is null then          select seq_analysisdataset.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR procdsruns.ID using SEQ seq_procdsruns

 CREATE OR REPLACE TRIGGER procdsruns_TRIG before insert on procdsruns    for each row begin     if inserting then       if :NEW.ID is null then          select seq_procdsruns.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR procdstier.ID using SEQ seq_procdstier

 CREATE OR REPLACE TRIGGER procdstier_TRIG before insert on procdstier    for each row begin     if inserting then       if :NEW.ID is null then          select seq_procdstier.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR procdsparent.ID using SEQ seq_procdsparent

 CREATE OR REPLACE TRIGGER procdsparent_TRIG before insert on procdsparent    for each row begin     if inserting then       if :NEW.ID is null then          select seq_procdsparent.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR procalgo.ID using SEQ seq_procalgo

 CREATE OR REPLACE TRIGGER procalgo_TRIG before insert on procalgo    for each row begin     if inserting then       if :NEW.ID is null then          select seq_procalgo.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR block.ID using SEQ seq_block

 CREATE OR REPLACE TRIGGER block_TRIG before insert on block    for each row begin     if inserting then       if :NEW.ID is null then          select seq_block.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR files.ID using SEQ seq_files

 CREATE OR REPLACE TRIGGER files_TRIG before insert on files    for each row begin     if inserting then       if :NEW.ID is null then          select seq_files.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filetier.ID using SEQ seq_filetier

 CREATE OR REPLACE TRIGGER filetier_TRIG before insert on filetier    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filetier.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR fileparentage.ID using SEQ seq_fileparentage

 CREATE OR REPLACE TRIGGER fileparentage_TRIG before insert on fileparentage    for each row begin     if inserting then       if :NEW.ID is null then          select seq_fileparentage.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filerunlumi.ID using SEQ seq_filerunlumi

 CREATE OR REPLACE TRIGGER filerunlumi_TRIG before insert on filerunlumi    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filerunlumi.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filealgo.ID using SEQ seq_filealgo

 CREATE OR REPLACE TRIGGER filealgo_TRIG before insert on filealgo    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filealgo.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR filebranch.ID using SEQ seq_filebranch

 CREATE OR REPLACE TRIGGER filebranch_TRIG before insert on filebranch    for each row begin     if inserting then       if :NEW.ID is null then          select seq_filebranch.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR analysisdsfilelumi.ID using SEQ seq_analysisdsfilelumi

 CREATE OR REPLACE TRIGGER analysisdsfilelumi_TRIG before insert on analysisdsfilelumi    for each row begin     if inserting then       if :NEW.ID is null then          select seq_analysisdsfilelumi.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ====================================================
-- AUTO INC TRIGGER FOR seblock.ID using SEQ seq_seblock

 CREATE OR REPLACE TRIGGER seblock_TRIG before insert on seblock    for each row begin     if inserting then       if :NEW.ID is null then          select seq_seblock.nextval into :NEW.ID from dual;       end if;    end if; end;
/

-- ========= TIME STAMP TRIGGERS =======================

PROMPT Creating timestamp triggers
-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSperson BEFORE INSERT OR UPDATE ON person
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSrole BEFORE INSERT OR UPDATE ON role
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSassignedrole BEFORE INSERT OR UPDATE ON assignedrole
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSphysicsgroup BEFORE INSERT OR UPDATE ON physicsgroup
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSschemaversion BEFORE INSERT OR UPDATE ON schemaversion
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSruns BEFORE INSERT OR UPDATE ON runs
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSdatatier BEFORE INSERT OR UPDATE ON datatier
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSlumisection BEFORE INSERT OR UPDATE ON lumisection
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSbranch BEFORE INSERT OR UPDATE ON branch
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTStimelog BEFORE INSERT OR UPDATE ON timelog
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSdatatierorder BEFORE INSERT OR UPDATE ON datatierorder
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSappfamily BEFORE INSERT OR UPDATE ON appfamily
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSappversion BEFORE INSERT OR UPDATE ON appversion
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSappexecutable BEFORE INSERT OR UPDATE ON appexecutable
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSqueryableparameterset BEFORE INSERT OR UPDATE ON queryableparameterset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSparameterbinding BEFORE INSERT OR UPDATE ON parameterbinding
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTStriggerpathdescription BEFORE INSERT OR UPDATE ON triggerpathdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSmcdescription BEFORE INSERT OR UPDATE ON mcdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSotherdescription BEFORE INSERT OR UPDATE ON otherdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilestatus BEFORE INSERT OR UPDATE ON filestatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfiletype BEFORE INSERT OR UPDATE ON filetype
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilevalidstatus BEFORE INSERT OR UPDATE ON filevalidstatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdstype BEFORE INSERT OR UPDATE ON analysisdstype
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdsstatus BEFORE INSERT OR UPDATE ON analysisdsstatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdsdef BEFORE INSERT OR UPDATE ON analysisdsdef
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSstorageelement BEFORE INSERT OR UPDATE ON storageelement
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdsstatus BEFORE INSERT OR UPDATE ON procdsstatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprimarydstype BEFORE INSERT OR UPDATE ON primarydstype
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSalgorithmconfig BEFORE INSERT OR UPDATE ON algorithmconfig
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprimarydatasetdescription BEFORE INSERT OR UPDATE ON primarydatasetdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprimarydataset BEFORE INSERT OR UPDATE ON primarydataset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocesseddataset BEFORE INSERT OR UPDATE ON processeddataset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdataset BEFORE INSERT OR UPDATE ON analysisdataset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdsruns BEFORE INSERT OR UPDATE ON procdsruns
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdstier BEFORE INSERT OR UPDATE ON procdstier
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdsparent BEFORE INSERT OR UPDATE ON procdsparent
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocalgo BEFORE INSERT OR UPDATE ON procalgo
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSblock BEFORE INSERT OR UPDATE ON block
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfiles BEFORE INSERT OR UPDATE ON files
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfiletier BEFORE INSERT OR UPDATE ON filetier
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfileparentage BEFORE INSERT OR UPDATE ON fileparentage
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilerunlumi BEFORE INSERT OR UPDATE ON filerunlumi
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilealgo BEFORE INSERT OR UPDATE ON filealgo
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilebranch BEFORE INSERT OR UPDATE ON filebranch
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdsfilelumi BEFORE INSERT OR UPDATE ON analysisdsfilelumi
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSseblock BEFORE INSERT OR UPDATE ON seblock
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSperson BEFORE INSERT OR UPDATE ON person
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSrole BEFORE INSERT OR UPDATE ON role
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSassignedrole BEFORE INSERT OR UPDATE ON assignedrole
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSphysicsgroup BEFORE INSERT OR UPDATE ON physicsgroup
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSschemaversion BEFORE INSERT OR UPDATE ON schemaversion
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSruns BEFORE INSERT OR UPDATE ON runs
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSdatatier BEFORE INSERT OR UPDATE ON datatier
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSlumisection BEFORE INSERT OR UPDATE ON lumisection
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSbranch BEFORE INSERT OR UPDATE ON branch
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTStimelog BEFORE INSERT OR UPDATE ON timelog
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSdatatierorder BEFORE INSERT OR UPDATE ON datatierorder
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSappfamily BEFORE INSERT OR UPDATE ON appfamily
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSappversion BEFORE INSERT OR UPDATE ON appversion
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSappexecutable BEFORE INSERT OR UPDATE ON appexecutable
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSqueryableparameterset BEFORE INSERT OR UPDATE ON queryableparameterset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSparameterbinding BEFORE INSERT OR UPDATE ON parameterbinding
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTStriggerpathdescription BEFORE INSERT OR UPDATE ON triggerpathdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSmcdescription BEFORE INSERT OR UPDATE ON mcdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSotherdescription BEFORE INSERT OR UPDATE ON otherdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilestatus BEFORE INSERT OR UPDATE ON filestatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfiletype BEFORE INSERT OR UPDATE ON filetype
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilevalidstatus BEFORE INSERT OR UPDATE ON filevalidstatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdstype BEFORE INSERT OR UPDATE ON analysisdstype
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdsstatus BEFORE INSERT OR UPDATE ON analysisdsstatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdsdef BEFORE INSERT OR UPDATE ON analysisdsdef
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSstorageelement BEFORE INSERT OR UPDATE ON storageelement
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdsstatus BEFORE INSERT OR UPDATE ON procdsstatus
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprimarydstype BEFORE INSERT OR UPDATE ON primarydstype
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSalgorithmconfig BEFORE INSERT OR UPDATE ON algorithmconfig
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprimarydatasetdescription BEFORE INSERT OR UPDATE ON primarydatasetdescription
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprimarydataset BEFORE INSERT OR UPDATE ON primarydataset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocesseddataset BEFORE INSERT OR UPDATE ON processeddataset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdataset BEFORE INSERT OR UPDATE ON analysisdataset
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdsruns BEFORE INSERT OR UPDATE ON procdsruns
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdstier BEFORE INSERT OR UPDATE ON procdstier
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocdsparent BEFORE INSERT OR UPDATE ON procdsparent
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSprocalgo BEFORE INSERT OR UPDATE ON procalgo
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSblock BEFORE INSERT OR UPDATE ON block
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfiles BEFORE INSERT OR UPDATE ON files
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfiletier BEFORE INSERT OR UPDATE ON filetier
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfileparentage BEFORE INSERT OR UPDATE ON fileparentage
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilerunlumi BEFORE INSERT OR UPDATE ON filerunlumi
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilealgo BEFORE INSERT OR UPDATE ON filealgo
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSfilebranch BEFORE INSERT OR UPDATE ON filebranch
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSanalysisdsfilelumi BEFORE INSERT OR UPDATE ON analysisdsfilelumi
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- ====================================================
-- LastModified Time Stamp Trigger

CREATE OR REPLACE TRIGGER TRTSseblock BEFORE INSERT OR UPDATE ON seblock
FOR EACH ROW
BEGIN
  :NEW.LASTMODIFICATIONDATE := SYSTIMESTAMP;
END;
/

-- Set the Schema Version -- 
INSERT INTO SchemaVersion(SCHEMAVERSION, CREATIONDATE) values ('v00_00_06', SYSTIMESTAMP);
-- Pre Fill some information into tables ---------
INSERT INTO AnalysisDSStatus (Status) VALUES ('NEW');
INSERT INTO FileStatus (Status) VALUES ('VALID');
INSERT INTO FileStatus (Status) VALUES ('INVALID');
INSERT INTO FileStatus (Status) VALUES ('MERGED');
INSERT INTO FileStatus (Status) VALUES ('PROMOTED');
INSERT INTO ProcDSStatus (Status) VALUES ('VALID');
INSERT INTO ProcDSStatus (Status) VALUES ('INVALID');
INSERT INTO ProcDSStatus (Status) VALUES ('PROMOTED');
INSERT INTO FileType(Type) VALUES ('EVD') ;
INSERT INTO AnalysisDSType(Type) VALUES ('TEST');
INSERT INTO PrimaryDSType  (Type) VALUES ('VALID');
INSERT INTO Person(Name, DistinguishedName, ContactInfo, CreationDate) Values ('DBSUSER', 'NODN', 'WH', SYSTIMESTAMP);
INSERT INTO FileValidStatus (Status, CreationDate) VALUES ('VALID', SYSTIMESTAMP);
INSERT INTO FileValidStatus (Status, CreationDate) VALUES ('INVALID', SYSTIMESTAMP);
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("GEN", "Generator output, four vectors and vertices in vacuum. For example, pythia events HepMCProduct");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("SIM", "Simulated output from GEANT/OSCAR processing of GEN data  PSimHitContainer, EmbdSimVertexContainer, PCaloHitContainer, CrossingFrame");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("DIGI", "Digitixed output from the various Digitizers that act on the SIM data    EBDigiCollection, HBHEDigiCollection, HFDigiCollection, StripDigiCollection, CSCStripDigiCollection, CSCWireDigiCollection");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("RECO", "Reconstructed products produced from either real data or DIGI data       TBA");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("AOD", "Analysis Object Data products TBA");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("RAW", "Raw detector output from the HLT system   TBA");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("ALCARECO", "IS ITS A TIER ? TBA");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("USER", "Things that users make afte AOD. The analysis equivalent of the kitchen sink TBA");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("GEN-SIM", "Generator output, four vectors and vertices in vacuum. For example, pythia events HepMCProduct");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("GEN-SIM-DIGI", "Generator output, four vectors and vertices in vacuum. For example, pythia events HepMCProduct");
--  INSERT INTO DataTierOrder(DataTierOrder, Description) VALUES ("GEN-SIM-DIGI-RECO", "Generator output, four vectors and vertices in vacuum. For example, pythia events HepMCProduct");
INSERT INTO DataTier (Name, CreationDate) VALUES ('GEN', SYSTIMESTAMP);
INSERT INTO DataTier (Name, CreationDate) VALUES ('SIM', SYSTIMESTAMP);
INSERT INTO DataTier (Name, CreationDate) VALUES ('DIGI', SYSTIMESTAMP);
INSERT INTO DataTier (Name, CreationDate) VALUES ('RECO', SYSTIMESTAMP);
INSERT INTO DataTier (Name, CreationDate) VALUES ('ALCARECO', SYSTIMESTAMP);
INSERT INTO DataTier (Name, CreationDate) VALUES ('USER', SYSTIMESTAMP);
commit;
