sqlite3 test.db  "drop table t2;"
sqlite3 test.db  "drop table t1;"
sqlite3 test.db  "create table t1 (t1key INTEGER PRIMARY KEY,data VARCHAR(30),num INTEGER,timeEnter DATE);"
sqlite3 test.db  "insert into t1 (t1key, data, num) values (1,'This is sample data',3);"
sqlite3 test.db  "insert into t1 (t1key, data, num) values (2,'More sample data',6);"
sqlite3 test.db  "insert into t1 (t1key, data, num) values (3,'And a little more',9);"
sqlite3 test.db  "create table t2 (t2key INTEGER PRIMARY KEY, t1key INTEGER, num INTEGER,timeEnter DATE,FOREIGN KEY (t1key) REFERENCES t1(t1key));"
