ALTER TABLE NATION   drop CONSTRAINT fk_nat_region;
ALTER TABLE SUPPLIER drop CONSTRAINT fk_sup_nation;
ALTER TABLE CUSTOMER drop CONSTRAINT fk_cus_nation;
ALTER TABLE PARTSUPP drop CONSTRAINT fk_par_supplier;
ALTER TABLE PARTSUPP drop CONSTRAINT fk_par_part;
ALTER TABLE ORDERS   drop CONSTRAINT fk_ord_customer;
ALTER TABLE LINEITEM drop CONSTRAINT fk_lin_orders;
ALTER TABLE LINEITEM drop CONSTRAINT fk_lin_partsupp;

ALTER TABLE REGION DROP PRIMARY KEY;
ALTER TABLE NATION DROP PRIMARY KEY;
ALTER TABLE PART DROP PRIMARY KEY;
ALTER TABLE SUPPLIER DROP PRIMARY KEY;
ALTER TABLE PARTSUPP DROP PRIMARY KEY;
ALTER TABLE ORDERS DROP PRIMARY KEY;
ALTER TABLE LINEITEM DROP PRIMARY KEY;
ALTER TABLE CUSTOMER DROP PRIMARY KEY;

DROP TABLE REGION;
DROP TABLE NATION;
DROP TABLE PART;
DROP TABLE SUPPLIER;
DROP TABLE PARTSUPP;
DROP TABLE ORDERS;
DROP TABLE LINEITEM;
DROP TABLE CUSTOMER;
